//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NagesenAsAService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localize {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localize() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NagesenAsAService.Localize", typeof(Localize).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow &quot;Dis&quot; coin.
        /// </summary>
        public static string AllowDisCoin {
            get {
                return ResourceManager.GetString("AllowDisCoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 投げ銭というカタチでリアルタイムで発表者を評価するWebアプリ「投げ銭BOX」のSaaSです。.
        /// </summary>
        public static string appDescription {
            get {
                return ResourceManager.GetString("appDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 投げ銭,投げ銭 as a Service,投げ銭BOX,投げ銭BOX as a Service,NaaS.
        /// </summary>
        public static string appKeywords {
            get {
                return ResourceManager.GetString("appKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset this room? (All count of coins will be 0).
        /// </summary>
        public static string ConfirmResetRoom {
            get {
                return ResourceManager.GetString("ConfirmResetRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter room number..
        /// </summary>
        public static string EnterRoomNumber {
            get {
                return ResourceManager.GetString("EnterRoomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you leave this page, you lost coins image..
        /// </summary>
        public static string IfYouLeaveThisPageYouLostCoinsImage {
            get {
                return ResourceManager.GetString("IfYouLeaveThisPageYouLostCoinsImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops... the room number #{0} is no longer available..
        /// </summary>
        public static string OopsTheRoomNumberIsNoLongerAvailable {
            get {
                return ResourceManager.GetString("OopsTheRoomNumberIsNoLongerAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or Create New Room.
        /// </summary>
        public static string OrCreateNewRoom {
            get {
                return ResourceManager.GetString("OrCreateNewRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or create your own new room from &lt;a id=&quot;btn-create-new-room&quot; class=&quot;no-effects&quot;&gt;click here.&lt;/a&gt;.
        /// </summary>
        public static string OrCreateYourOwnNewRoomFromClickHere {
            get {
                return ResourceManager.GetString("OrCreateYourOwnNewRoomFromClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please &lt;a href=&apos;{0}&apos;&gt;go back to home&lt;/a&gt; and enter correct room number,.
        /// </summary>
        public static string PleaseGoBackToHomeAndEnterCorrectRoomNumber {
            get {
                return ResourceManager.GetString("PleaseGoBackToHomeAndEnterCorrectRoomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResetRoom {
            get {
                return ResourceManager.GetString("ResetRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string SessionTitle {
            get {
                return ResourceManager.GetString("SessionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The room will expire after 7 days..
        /// </summary>
        public static string TheRoomWillExpireAfter7days {
            get {
                return ResourceManager.GetString("TheRoomWillExpireAfter7days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Hashtag.
        /// </summary>
        public static string TwitterHashtag {
            get {
                return ResourceManager.GetString("TwitterHashtag", resourceCulture);
            }
        }
    }
}
